name: dicoding_final
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  auto_route: ^7.8.4
  bloc_test: ^9.1.5
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  floor: ^1.4.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  get_it: ^7.6.4
  http: ^1.1.2
  internet_connection_checker_plus: ^2.1.0
  lottie: ^2.7.0
  mocktail: ^1.0.2
  salomon_bottom_bar: ^3.3.2
  sqflite: ^2.3.0
  very_good_analysis: ^5.1.0

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.7
  floor_generator: ^1.4.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/font/montserrat/
    - assets/json/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/font/montserrat/Montserrat-Black.ttf
          weight: 900
        - asset: assets/font/montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/font/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/font/montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/font/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/font/montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/font/montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/font/montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/font/montserrat/Montserrat-Thin.ttf
          weight: 100
